### ISSUE TITLE
Support multiple main files

### ISSUE THREAD

**Issue by joeandaverde** [rtfeldman/node-elm-compiler#26]
`elm-make` supports multiple main files by specifying each elm file to the make command.

**Comment by rtfeldman** [comment]
Thanks for reporting! I want to implement things based on use cases that are blocking current development, so I'm gonna close this until someone encounters one.

**Comment by paulstatezny** [comment]
@rtfeldman What do you mean by "blocking current development"?

My use case involves multiple Elm apps on a page, and I've been using @joeandaverde's [elm-webpack-project-loader](https://github.com/joeandaverde/elm-webpack-project-loader) to get around the lack of this feature.

Except recent changes to elm-webpack-project-loader are leaving it in a broken state for me. Can we finally add support for this?

**Comment by rtfeldman** [comment]
@paulstatenzy what I mean by that is something exactly like your use case. I don't want to add features without clear motivation first. ☺️

Please open a new issue describing your use case and I'll revisit this.

> Can we finally add support for this?

I get that you're frustrated, but I can't read your mind to know what you're building, and I'm not going to add features that don't have a motivating use case. There's no call for the attitude implicit in the "finally" here.

**Comment by paulstatezny** [comment]
@rtfeldman That makes sense. I appreciate the thoughtful approach that you and Evan have, keeping things focused and protecting against feature creep.

I'd be glad to open up an issue describing my use case. I should probably first look more closely at the relationship between `node-elm-compiler` and `elm-webpack-loader` to ensure I'm making a request that makes sense.

> There's no call for the attitude implicit in the "finally" here.

I admit there was some frustration there, and it was impolite to ask that way. I bet it came across rude or entitled. I'm sorry for the offense. I certainly appreciate your work on this tool and Elm as a whole, but my comment didn't reflect that.

**Comment by rtfeldman** [comment]
❤️ Thank you for the awesome attitude @paulstatezny - I really appreciate it!
