### ISSUE TITLE
findAllDependencies can be very slow

### ISSUE THREAD

**Issue by opsb** [rtfeldman/node-elm-compiler#46]
I stumbled across this using https://github.com/rtfeldman/elm-webpack-loader. I was getting extremely slow build times (60 seconds+) even though elm would compile the code in under a second. I traced it to https://github.com/rtfeldman/elm-webpack-loader/blob/master/index.js#L45 which was what was taking the majority of the 60 seconds. As a temporary fix for elm-webpack-loader I did a simple file system search for elm files which is good enough for our case https://github.com/zapnito/elm-webpack-loader/blob/master/index.js#L56. 

I'm not sure what the best fix is here. One strategy might be to grab the src folders from elm-package.json and do a recursive search for all *.elm files. Perhaps the existing implementation solves a scenario this wouldn't satisfy though? (I suppose it will avoid the inclusion of any files that aren't imported anywhere). Another option would be to add a solution specifically to elm-webpack-loader and leave this one alone.

**Comment by eeue56** [comment]
published as 4.0.0 in elm-webpack-loader, this now does things in a better way.

**Comment by opsb** [comment]
thanks!
