### ISSUE TITLE
compileToStringSync?

### ISSUE THREAD

**Issue by mockdeep** [rtfeldman/node-elm-compiler#60]
Not sure if this is the right use case, but I'm trying to integrate Elm into my React application. My tests are all in Jest and it would be nice if I could keep them passing during the transition. I'm trying to get this working as a [Jest transform](https://facebook.github.io/jest/docs/en/configuration.html#transform-object-string-string), but they require synchronous compilation, and it looks like they [have no intention of supporting](https://github.com/facebook/jest/issues/4485) an asynchronous transform. Is there any possibility of getting a synchronous version of `compileToString`?

**Comment by rtfeldman** [comment]
I'd be happy to accept a PR for it!

Looks like it'd need to use [`child_process.execFileSync`](https://nodejs.org/api/child_process.html#child_process_child_process_execfilesync_file_args_options) and `temp.openSync` instead of `temp.open`.

**Comment by mockdeep** [comment]
@rtfeldman Alright, I've PR'd the new helper, however it looks like my assumptions were wrong on what the result would be. I'm now successfully compiling my Elm to JS, but it looks like the Elm component doesn't get properly "rendered" using Jest and Enzyme. This might not be the best place to ask, but any advice on how to get a simple Elm app to render out its text? I've got a basic static component:

```elm
port module Welcome exposing (main)

import Html exposing (div, p, text)

main : Program Never (Never -> a) Never
main =
  Html.beginnerProgram { model = never, view = view, update = never }

view : never -> Html.Html msg
view never =
  div []
  [ p [] [ text "Welcome!!!" ]
  , p [] [ text "the bananas are over there" ]
  ]
```

And I'm using an [updated version](https://blog.boon.gl/2017/11/28/react-elm-wrapper.html) of [`react-elm-components`](https://github.com/evancz/react-elm-components). Against that component, I'm just expecting the text `"Welcome!!!"` to be in the rendered component.

**Comment by eeue56** [comment]
@mockdeep I don't quite follow the question, but if you're trying to do stuff with Html then you need to use elm-static-html-lib or elm-html-test.

**Comment by mockdeep** [comment]
@eeue56 thanks for the information. To clarify a bit, I've mounted an Elm app inside of a React component, which works for me when I boot up my server and navigate to the page (I see the "Welcome!!!" text). However, I have tests written in JavaScript using the [Jest](https://facebook.github.io/jest/) testing framework and [Enzyme](https://github.com/airbnb/enzyme) for rendering the React components.

What I'm trying to accomplish is to have a way to gradually convert the React to Elm while minimally changing the tests. Adding this `renderToStringSync` compiler gets me a step closer, but it looks like there's still something that triggers Elm to render into the page when I visit it in the browser which doesn't get triggered in the tests. Not sure if it's the right direction, but one thought is maybe whether I could pluck the Elm app out of the components in the test and render it to static html using your [`elm-static-html-lib`](https://github.com/eeue56/elm-static-html-lib), but not too sure.
