### ISSUE TITLE
Remove stale branches

### ISSUE THREAD

**Issue by Y0hy0h** [rtfeldman/node-elm-compiler#82]
[Most branches](https://github.com/rtfeldman/node-elm-compiler/branches) on this repo are already merged. Only [`read-deps`](https://github.com/rtfeldman/node-elm-compiler/tree/read-deps) is not, but that is behind master by more than 200 commits.

I would suggest removing all these branches to keep the repo tidy.

**Comment by avh4** [comment]
Thanks, I cleaned up the merged ones.
