### ISSUE TITLE
lodash's vulnerabilities strike again

### ISSUE THREAD

**Issue by ulisses-alves** [rtfeldman/node-elm-compiler#96]
There's a couple new vulnerabilities being reported by npm audit in regards to lodash:

![image](https://user-images.githubusercontent.com/767662/61293158-5d7e3100-a7d3-11e9-8306-a7655e36651b.png)

**Comment by avh4** [comment]
This should be fixed by https://github.com/rtfeldman/node-elm-compiler/pull/97

**Comment by DawidJanczak** [comment]
Would it be possible to push a new release with the fix? @avh4 @rtfeldman

**Comment by kachkaev** [comment]
➡️ #100

Needs merging and releasing 🙏

**Comment by smt116** [comment]
#100 is not enough as find-elm-dependencies is pinned to a version that is vulnerable too. I've prepared a PR that upgrades both dependencies and removed versions' pinning (see #101).
